project_id = "inowequchkiqgleluule"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[auth]
enabled = true
port = 54324
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://localhost:3000"]
jwt_expiry = 3600
refresh_token_rotation_enabled = true
access_token_expiry = 3600
refresh_token_expiry = 604800
enable_signup = true
double_confirm_changes = true

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = false
secure_nonce = true

[db]
port = 54322

[db.pooler]
enabled = false
port = 54329
pool_mode = "transaction"
default_pool_size = 20
max_client_conn = 100

[realtime]
enabled = true
port = 54323

[studio]
enabled = true
port = 54323

[inbucket]
enabled = true
port = 54324
smtp_port = 54325
pop3_port = 54326

[storage]
enabled = true
port = 54325
file_size_limit = "50MiB"

[functions]
verify_jwt = true

[functions.send-approval-email]
verify_jwt = false