// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://inowequchkiqgleluule.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imlub3dlcXVjaGtpcWdsZWx1dWxlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc3MDE0NjMsImV4cCI6MjA2MzI3NzQ2M30.3zodoCcCC6yCQCVPnPFLUGZs8gXJjkZuA-8xp5hoGn8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);